Change sitemap to use full URLs
saasquatch/saasquatch-docs pull request #181
Opened 2022-08-09 21:21 UTC by KeeganCK

## Description of the change

Just testing right now, but trying to use full links in sitemaps

## Types of changes

- [ ] Documentation content
- [ ] Page Layout / templates / structure
- [x] Internal / code cleanup / build system

2022-08-11 20:17 UTC, DerekSiemens commented
@KeeganCK Before merging this PR can you run a build to get us a copy of what the production sitemap would be - want us to review it and make sure google accepts it before launch

2022-09-07 23:27 UTC, johanventer requested changes

2022-09-07 23:27 UTC, johanventer commented on .gitignore
> +package-lock.json
Don't do this

2022-09-07 23:29 UTC, johanventer submitted a review, later dismissed

2022-09-08 16:19 UTC, johanventer approved these changes

2022-09-08 16:19 UTC, merged